### ISSUE TITLE
Is regel 2.03.05.08 terecht?

### ISSUE THREAD

**Issue by MarkDirksen** [centrumvoorstandaarden/SBR_Werkgroep_NT#1]
link naar regel: https://xiffy.gitlab.io/nta-taxonomy-regels/#2.03.05.08

Wij (Visma Connect) zijn onlangs tegen regel 2.03.05.08 aangelopen. Ten eerste viel op dat de toelichting voor de regel zoals nu gepubliceerd geen uitleg geeft waarom een primary niet zowel dimensioneel als a-dimensioneel mag voorkomen binnen een entrypoint. Uit het verleden denken we dat de reden voor deze regel zou kunnen zijn dat de taxonomie zo expliciet mogelijk moet zijn. Als iemand hier meer ove weet zou opheldering mooi zijn.

Daarnaast zijn wij zijn van mening dat de regel geen goede toevoeging is aan de nta. Om de volgende redenen:

1. Het uitgangspunt dat een a-dimensioneel fact onvoldoende duidelijk is wanneer hetzelfde fact ook dimensioneel voorkomt valt te betwijfelen. (Aangenomen dat dat de reden van de regel is.) Indien een a-dimensioneel fact op zichzelf voldoende houvast geeft voor de rapporteur, zou dat nog steeds het geval zijn indien dezelfde primary ook dimensioneel voorkomt in het entry point.
2. De regel zoals nu opgesteld dekt onvoldoende de mogelijke scenario’s. Een primary kan twee keer dimensioneel voorkomen met gelijke dimensies en members waarbij één keer met een extra as. Dit valt nu buiten de regel maar is in essentie hetzelfde probleem.
3. Consistent toepassen van deze regel, in combinatie met de extra restricties volgend uit punt 2, zou praktisch niet toepasbaar zijn. Een goed voorbeeld is een balans waarbij de verschillende posten dimensioneel verder uitgesplitst worden. Waarbij de extra dimensie verschilt per post. Dan is de taxonomie ontwikkelaar genoodzaakt elk van deze dimensies toe te voegen aan de balansposten. Dit veroorzaakt een onwerkbare situatie.

Bij een taxonomie als de KvK is deze regel niet van toepassing omdat vrijwel overal twee "standaard" assen zijn toegevoegd (FinancialStatementTypeAxis en BasisOfPreparationAxis). Alleen als de regel wordt uitgebreid (zie punt 2) is de regel relevant voor de KvK taxonomie. Indat geval zou de regel ook veelvuldig overtreden worden.

Ik ben benieuwd wat de meningen zijn.

**Comment by ekaats** [comment]
Gefeliciteerd met issue nr1! Is de regel waar je naar verwijst wel degene die je bedoelt? Dit is de uitleg van 2.03.08.05: Van alle gebruikte labelrolen in de NT MOET een voorkomen in de lokale taal bestaan

Bedoel je deze regel misschien?
[2.03.05.09: Primaries in een entrypoint MOETEN allen dimensioneel of niet-dimensionaal zijn](https://xiffy.gitlab.io/nta-taxonomy-regels/#2.03.05.09)

**Comment by MarkDirksen** [comment]
Dank je! Verkeerd nummer inderdaad, ik bedoelde 2.03.05.08. 
2.03.05.09 lijkt er erg op, maar gaat over niet-dimensioneel (geen hypercube) ipv a-dimensioneel (hypercube zonder dimensies). Die twee haal ik ook vaak door elkaar ;)

**Comment by ekaatslogius** [comment]
Buiten gebruik gesteld
