### ISSUE TITLE
Parameters voor currency / entity / identifier / other

### ISSUE THREAD

**Issue by MarkDirksen** [centrumvoorstandaarden/SBR_Werkgroep_NT#13]
Dit is een wens / issue die al een tijd open staat. De originele wens was:

> Vanuit het formulier (entrypoint) kan er een instance worden gegenereerd. Hiervoor zou het formulier voldoende informatie moeten bevatten om dit te regelen.
> 
> - De contexten worden als volgt samengesteld
> - De scenarios kunnen bepaald worden aan de hand van de definitionLink (gelinked vanuit de tabel).
> - De perioden worden aangegeven via de tableLink en worden opgenomen in de generieke parameters
> - Alhoewel de identifier meestal in het report aanwezig is, heb ik geen aanknopingspunt om deze te bepalen.
> 
> Een generieke parameter, zou hier op zijn plaats zijn. Deze kunnen zelfs ook nog in de tabel worden opgenomen, conform de data. De scheme zou ook zo behandeld kunnen worden, maar dat is arbitrair. Hetzelfde geld voor de valuta.

 
**Concluderend is het dus gewenst om een mechanisme te hebben om automatisch alle aspecten in de instance te kunnen vullen. Van belang hierbij is het hebben van een uniforme werkwijze binnen de NT. Neem bijvoorbeeld de entity identifier in de kvk taxonomie. Er is geen parameter om deze waarde te vullen. Wél is er een formula die controleerd dat de juiste waarde gebruikt is (het kvk nummer).** 

Er zijn de volgende opties om dit te realiseren:

**1.a Aspect (unit, scheme, etc.) verplicht stellen d.m.v. een formula**
D.m.v. een formula kan worden afgedwongen dat een waarde _w_ voor aspect _a_ wordt gebruikt. Dit kan gelden voor alle (relevante) facts binnen een entrypoint, of voor een subset. De waarde kan tevens variabel zijn (afhankelijk van de inhoud van een instance).

**1.b Aspect afhankelijk maken van een parameter d.m.v. een formula.**
Voortboordurend op 1.a kan de waarde _w_ als parameter meegenomen orden in de taxonomie. Deze wordt vervolgens gebruikt in een formula. Er is geen verschil in werking tussen 1.a en 1.b. De parameter kan wel als documentatie dienen en kan direct uitgevraagd worden. Het kan dan nuttig zijn deze parameter volgens een bepaalde naamgevingsconventie op te stellen zodat deze herkent kan worden als bijvoorbeeld de entity identifier.

**2.a Tabellen definiëren die het aspect specificeren.**
Net zoals gedaan is voor de periode, kan een tabel specificeren welke aspect waarde getoond (gebruikt) moet worden. Hiervoor kan een vaste waarde gespecificeerd worden die eventueel per tabel, rij en/of kolom kan verschillen.
Hoewel het binnen de NT gebruikelijk is om de te rapporteren facts binnen de tabel definities te houden is het belangrijk te noemen dat het technisch wél mogelijk is om facts te rapporteren die buiten enige tabel vallen. 

**2.b Tabellen definiëren die het aspect specificeren afhankelijk van een parameter.**
Net zoals bij 1.b kan de aspect waarde vanuit een parameter gevuld worden, zoals ook bij de periode gedaan is. Dit maakt het mogelijk de waarde afhankelijk te maken van facts uit de instance.

**3 Enkel een parameter opnemen.**
Tot slot de optie om voor een aspect een standaard waarde als parameter op te nemen. Belangrijk om te realiseren dat er dan verder geen restrictie is op de instance XBRL-technisch gezien. De parameter dient dan als een soort documentatie. Om de instance dan automatisch  te vullen zouden afspraken gemaakt moeten worden welke parameter voor welk doeleinde gebruikt dient te worden. Daarnaast is deze optie alleen te gebruiken indien alle facts in de instance dezelfde waarde voor aspect a moeten krijgen.

Relevant voor de discussie is de volgende NTA regel: https://xiffy.gitlab.io/nta-taxonomy-regels/#2.03.04.10
De regel zegt dat aspecten die verschillende waardes kunnen hebben in de tabel definitie opgenomen moeten worden. Dit betekend dat enkel de aspecten die slechts één waarde hebben in de instance mogelijk niet in de tabel definitie opgenomen zijn.
Als voorbeeld in de KvK taxonomie zijn dat de entity identifier, scheme en de unit voor monetaire waarden.

**Comment by MarkDirksen** [comment]
Er is in de VT en de AGT geëxperimenteerd met parameters voor het unit aspect.

In de VT zit een parameter die de unit voor sqm (square meter) selecteerd:
`<variable:parameter as="xs:QName" id="areaUnitRefQName" name="areaUnitRefQName" required="false" select="xs:QName('utr:sqm')" xlink:label="areaUnitRefQName" xlink:type="resource"/>`
Deze wordt vervolgens gebruikt in een formula om voor alle concepten van het type "areaItemType" te controleren of de unit gelijk is aan utr:sqm.

In de AGT is een soortgelijke constructie toegepast, met het verschil dat er in de instance verschillende waardes gebruikt moeten worden. Dus soms sqm (square meter) en soms ha (hectare). De parameters:
`<variable:parameter as="xs:QName" id="unitQNameAreaHa" name="unitQNameAreaHa" required="false" select="xs:QName('utr:ha')" xlink:label="unitQNameAreaHa" xlink:type="resource"/>`
`<variable:parameter as="xs:QName" id="unitQNameAreaM2" name="unitQNameAreaM2" required="false" select="xs:QName('utr:sqm')" xlink:label="unitQNameAreaM2" xlink:type="resource"/>
`
worden wederom gebruikt in formulas, die voor specifieke facts ha óf sqm afdwingen.
Hier is voor gekozen ondanks de overtreding van regel https://xiffy.gitlab.io/nta-taxonomy-regels/#2.03.04.10 vanwege praktische overwegingen (ontwikkeltijd).

**Comment by ekaatslogius** [comment]
Dit wordt teruggekoppeld naar de EGG door Frank.
