### ISSUE TITLE
Regel 3.02.13.01 string vs stringItemType

### ISSUE THREAD

**Issue by tim-koelewijn** [centrumvoorstandaarden/SBR_Werkgroep_NT#2]
Nav de laatste WGNT en de NTA melding over het gebruik van string ipv stringItemType in een enum wat een typed dimension is het volgende:
- Regel 3.02.13.01 moet worden:
Een enumeration waarde MOET een restrictie zijn op xbrli:stringItemType als deze als type voor een concept wordt gebruikt.
Toelichting aanvullen met: Dit geldt alleen voor een concept waarop gerapporteerd kan worden. Een enumeration die gebruikt wordt als xbrldt:typedDomainRef wordt hiervan dus uitgesloten.

**Comment by MarkDirksen** [comment]
Ik moet zeggen dat ik de regel niet helemaal snap. Hoe bepaal je dat een enumeration waarde een restrictie op xbrli:stringItemType is?

**Comment by tim-koelewijn** [comment]
Tja dat onderdeel van de regel heb ik niet aangepast. Lijkt ook nogal wat overlap met 2.02.07.04 te hebben. Weet iemand het onderscheid? Waarom de een in de 2 reeks en de ander in de 3 reeks? En zouden we wellicht nog iets moeten roepen over dat als het geen concept is je een xs:string als value moet nemen? Dat is nl hetgeen men blijkbaar in heet verleden heeft proberen te regelen met deze regels de notes erbij lezende, dat er geen ander type wordt gebruikt.

**Comment by MarkDirksen** [comment]
Dit is een voorbeeld van een enumeratie definitie:


<xs:simpleType id="bzk-ww-sim-codes_typeofpropertySimpleType" name="typeofpropertySimpleType">  
&nbsp;<xs:restriction **base="xs:string">**
&nbsp;&nbsp;<xs:enumeration id="bzk-ww-sim-codes_TypeOfProperty_CommercialRealEstate" value="Bedrijfsruimte"/>
&nbsp;&nbsp;<xs:enumeration id="bzk-ww-sim-codes_TypeOfProperty_IntramuralHealthcareRealEstate" value="Intramuraal zorgvastgoed"/>
&nbsp;&nbsp;<xs:enumeration id="bzk-ww-sim-codes_TypeOfProperty_SocialRealEstate" value="Maatschappelijk vastgoed"/>
&nbsp;&nbsp;<xs:enumeration id="bzk-ww-sim-codes_TypeOfProperty_Other" value="Overig"/>
&nbsp;&nbsp;<xs:enumeration id="bzk-ww-sim-codes_TypeOfProperty_ParkingFacilities" value="Parkeergelegenheid"/>
&nbsp;&nbsp;<xs:enumeration id="bzk-ww-sim-codes_TypeOfProperty_LivingSpace" value="Woonruimte"/>
&nbsp;</xs:restriction>
</xs:simpleType>

Waarbij 2.02.07.04 slaat op het dikgedrukte denk ik. Waar deze regel dan precies over gaat weet ik niet. 
3.02.13.01 valt onder Naamgeving - Enumeratie waarden zie ik.

**Comment by tim-koelewijn** [comment]
Naamgeving? Hmm ik kan er nog niet zo veel mee. Wat dekt ie af wat 2.02.07.04 niet afdekt? Als ie niets afdekt, dan verwijderen. Wat betekent trouwen NA in de toelichting, not active?

**Comment by MarkDirksen** [comment]
Not Available denk ik.

**Comment by tim-koelewijn** [comment]
Tja, en die zouden we nu goed kunnen gebruiken ;)

**Comment by MarkDirksen** [comment]
Bij ons is deze regel geïmplementeerd zoals ik zou 2.02.07.04 zou verwachten. Het voorbeeld dat hierboven staat gaat bij ons dus fout op 3.02.13.01 vanwege dikgedrukte. Dan lijkt me dat het duplicaten van elkaar zijn, maar 2.02.07.04 is veel logischer omschreven.

**Comment by ekaats** [comment]
Ik heb de regels in JSON toegevoegd. De betreffende regel is hier te vinden:
https://github.com/centrumvoorstandaarden/SBR_Werkgroep_NT/blob/4b8ca59720eed90607ac297b3222faae7c9c2247/nta_regels/3_02_13_01.json
(alle regels: https://github.com/centrumvoorstandaarden/SBR_Werkgroep_NT/tree/main/nta_regels)

NA is inderdaad Not Available en is automatisch overgenomen vanuit de wiki. Misschien zou het mooier zijn om daar een null van te maken, maar daar zal ik nog wel even naar kijken.

Wat de dubbeling betreft weet ik ook niet wat de achterliggende gedachte is van deze regel.

**Comment by EKVK** [comment]
Goede morgen,

Ivm een coronatest ben ik vanmiddag niet aanwezig bij het NT overleg.

Met vriendelijke groet,

Ernst Dunnink
Dev Engineer, Informatie-analist, PO


***@***.******@***.***>
[KVK_logo_e-mail]<https://eur04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.kvk.nl%2F&data=04%7C01%7Cernst.dunnink%40kvk.nl%7C37886063a1e842123d6b08d90f1d3689%7C2b95cc4c4de24fcd9f8a6318b88ad7d3%7C0%7C0%7C637557440398143601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pQv18KHTCtSOIPGRqLaA8I11RI1fzI3Swuwf0KfZl98%3D&reserved=0>[KVK_social-logo_1_e-mail]<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnl-nl.facebook.com%2Fkamervankoophandel%2F&data=04%7C01%7Cernst.dunnink%40kvk.nl%7C37886063a1e842123d6b08d90f1d3689%7C2b95cc4c4de24fcd9f8a6318b88ad7d3%7C0%7C0%7C637557440398143601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=v7zv%2Bf4Afx%2BDGPbVZ%2FZNholazIwd9JcFi3ngo1j6OHc%3D&reserved=0>[KVK_social-logo_2_e-mail]<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fkamer-van-koophandel%2F&data=04%7C01%7Cernst.dunnink%40kvk.nl%7C37886063a1e842123d6b08d90f1d3689%7C2b95cc4c4de24fcd9f8a6318b88ad7d3%7C0%7C0%7C637557440398153560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=n2FP6uCQpe%2FyJDlVKkK2DGD2Eql%2FP2M95jIhz0eb32E%3D&reserved=0>[KVK_social-logo_3_e-mail]<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Fkvk_nl&data=04%7C01%7Cernst.dunnink%40kvk.nl%7C37886063a1e842123d6b08d90f1d3689%7C2b95cc4c4de24fcd9f8a6318b88ad7d3%7C0%7C0%7C637557440398153560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uwa%2BfZEsjIef35OjrnRnByCfTUxuSICnRQIa6o0efB8%3D&reserved=0>[KVK_social-logo_4_e-mail]<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fchannel%2FUCt8aMxjQlPaKqUDdI0R8NDQ&data=04%7C01%7Cernst.dunnink%40kvk.nl%7C37886063a1e842123d6b08d90f1d3689%7C2b95cc4c4de24fcd9f8a6318b88ad7d3%7C0%7C0%7C637557440398163512%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GENZ%2BQTrSSj3aF7nyRV%2ByHYkeNi4WJHHHuzdOWx%2FqA4%3D&reserved=0>
Sint Jacobsstraat 300
3511 BT Utrecht
www.kvk.nl<https://eur04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.kvk.nl%2F&data=04%7C01%7Cernst.dunnink%40kvk.nl%7C37886063a1e842123d6b08d90f1d3689%7C2b95cc4c4de24fcd9f8a6318b88ad7d3%7C0%7C0%7C637557440398163512%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ydj6ILCbaOpID9mCC1sCELbTJykla1ZabX1iv9Li4pw%3D&reserved=0>
[20184079_Digitale-handtekening-Innovatie-november-2018_181101]<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.kvk.nl%2Fadvies-en-informatie%2Finnovatie%2F&data=04%7C01%7Cernst.dunnink%40kvk.nl%7C37886063a1e842123d6b08d90f1d3689%7C2b95cc4c4de24fcd9f8a6318b88ad7d3%7C0%7C0%7C637557440398163512%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7d5S1Zlvjsd916jYTCuNba1d5tec%2FmQz6VZD04u3%2BD8%3D&reserved=0>

Van: tim-koelewijn ***@***.***>
Verzonden: dinsdag 8 juni 2021 16:12
Aan: centrumvoorstandaarden/SBR_Werkgroep_NT ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: Re: [centrumvoorstandaarden/SBR_Werkgroep_NT] Regel 3.02.13.01 string vs stringItemType (#2)


Tja, en die zouden we nu goed kunnen gebruiken ;)

-

**Comment by ekaats** [comment]
Deze regel lijkt een duplicaat van 2.02.07.04. Tijdens de bijeenkomst van de WG NT hebben we besloten deze regel buiten gebruik te stellen.

**Comment by ekaatslogius** [comment]
Buiten gebruik gesteld
