### ISSUE TITLE
Uitleg taxonomy package naar github

### ISSUE THREAD

**Issue by tim-koelewijn** [centrumvoorstandaarden/SBR_Werkgroep_NT#28]
Zie https://github.com/centrumvoorstandaarden/SBR_Werkgroep_NT/blob/main/meeting_notes/20211207_Verslag_Werkgroep_NT.md#rondvraag.

**Comment by ekaatslogius** [comment]
Ik heb een begin gemaakt:
https://github.com/centrumvoorstandaarden/SBR_Werkgroep_NT/pull/37

Misschien gelijk een goede vraag voor onze eigen implementatie van taxo packages; is het een idee om ` <tp:languages> ` per package en EP verplicht te stellen? het is nu nogal gissen welke talen worden ondersteund. Het is bij benadering te herleiden uit de hoeveelheid labels in een specifieke taal, maar dit wil in de praktijk nog wel eens verschillen. De uitleg hierachter is vrij kort:
`The <tp:languages> element MAY be used to provide a list of languages available for an entry point.`
Dat interpreteer ik als een lijst met talen waarvoor (voldoende?) labels aanwezig zijn, niet perse in welke talen aangeleverd mag worden. Wat jullie?

**Comment by ekaatslogius** [comment]
Goed bevonden
