### ISSUE TITLE
Regel 2.02.07.04 string vs stringItemType

### ISSUE THREAD

**Issue by tim-koelewijn** [centrumvoorstandaarden/SBR_Werkgroep_NT#3]
Nav de laatste WGNT en de NTA melding over het gebruik van string ipv stringItemType in een enum wat een typed dimension is het volgende:
- Regel 2.02.07.04 moet worden:
<xs:enumeration> MOET <xs:restriction base=xbrli:stringItemType/> gebruiken als deze als type voor een concept wordt gebruikt.
Toelichting aanvullen met: Dit geldt alleen voor een concept waarop gerapporteerd kan worden. Een enumeration die gebruikt wordt als xbrldt:typedDomainRef wordt hiervan dus uitgesloten.

**Comment by MarkDirksen** [comment]
Eens, een typed member zal nooit substitutiongroup "item" hebben omdat een "item" een type moet hebben afgeleid van een XBRL base type (zoals bijvoorbeeld stringItemType).  Dit betekend dat een typed member geen concept is.
Dus lijkt me helemaal goed

Relevante referenties naar de spec.
http://www.xbrl.org/specification/XBRL-2.1/REC-2003-12-31/XBRL-2.1-REC-2003-12-31+corrected-errata-2013-02-20.html#concept
http://www.xbrl.org/Specification/XBRL-2.1/REC-2003-12-31/XBRL-2.1-REC-2003-12-31+corrected-errata-2013-02-20.html#_5.1.1.3

**Comment by ekaats** [comment]
In de WG NT is besloten om ook "xs:string" toe te staan voor typedDomainRef's aangezien het gebruik van "xbrli:stringItemType"  voor 'normaal'  gebruik al wordt afgewongen vanuit XBRL. Ik zal deze regel aanpassen.

**Comment by MarkDirksen** [comment]
Jochem wees mij er op dat tuples ook binnen de definitie van concept vallen, maar die hebben geen type. Om deze reden zou ik er van maken:

xs:enumeration MOET <xs:restriction base=xbrli:stringItemType/> gebruiken als deze als type voor schema element definities wordt gebruikt, waarbij het element xbrli:item als substitutionGroup heeft.

**Comment by MarkDirksen** [comment]
of we kunnen zeggen "cocepten met uitzondering van tuples". dealer's choice :)

**Comment by ekaatslogius** [comment]
Toegevoegd.
