### ISSUE TITLE
Assertion Severity 2.0

### ISSUE THREAD

**Issue by rdmgpzlx** [centrumvoorstandaarden/SBR_Werkgroep_NT#40]
Deze specificatie heeft bij XII de status van 'Proposed Recommendation' bereikt.

https://www.xbrl.org/Specification/assertion-severity/PR-2022-02-02/assertion-severity-PR-2022-02-02.html

Hiermee is het ook mogelijk om op een meer dynamische wijze een zwaarte van de bevinding toe te passen. Dit wordt gedaan door een XPATH 2.0 expressie toe te staan in dezelfde context als waar de assertion wordt geëvalueerd. Hierdoor kan een weging worden toegepast aan de hand van de uitkomst.

**Comment by ekaatslogius** [comment]
Besloten is om deze nieuwe specificatie nog niet toe te staan. Zodra er een use case voor is, dan kan er een RfC worden opgesteld.

Wel moeten we dit ter informatie met de EGG delen.

**Comment by tim-koelewijn** [comment]
Korte toelichting naar de EGG gegaan en er is besloten een RFC voor te schrijven.
