### ISSUE TITLE
Filing rules generaliseren?

### ISSUE THREAD

**Issue by rdmgpzlx** [centrumvoorstandaarden/SBR_Werkgroep_NT#43]
Filing rules worden als los Word document gepubliceerd.

https://sbr-nl.nl/sites/default/files/bestanden/taxonomie/SBR%20Filing%20Rules%20NT16%20-%2020210301_0.pdf

We kunnen deze generaliseren over domeinen (bd, kvk, etc) en als eigen (respec) document publiceren.

Ook kunnen we de regels op dezelfde manier als de NTA regels publiceren; vastgelegd in JSON bestanden en gegenereerd naar Respec.

**Comment by ekaatslogius** [comment]
KVK (NT16): https://sbr-nl.nl/sites/default/files/bestanden/taxonomie/20220101%20KvK%20Filing%20Rules%20NT%2016%20v1_0.pdf
BD (NT16): https://sbr-nl.nl/sites/default/files/bestanden/taxonomie/NT16_BD_20211208%20Reporting%20rules.pdf

**Comment by tim-koelewijn** [comment]
Volgende WGNT met Aad erbij bespreken

**Comment by rdmgpzlx** [comment]
Inhoudelijk valt er toch niet zoveel te generaliseren. Het voorbeeld wat ik vandaag noemde is mogelijk de enige:

`FR-KVK-1.01: Een XBRL instance document MOET de bestandsextensie .xbrl hebben`

Wat wel een interessante kandidaten zijn:

```
FR-KVK-5.01: Het attribuut ‘decimals’ bij monetaire waarden MOET worden gevuld met toegestane waarden
FR-KVK-5.02: Het attribuut ‘decimals’ bij niet-monetaire numerieke facts MOET worden gevuld met ‘INF’
```

Dit is gelieerd aan de 'noDecimals' discussie. Misschien goed om dat NT-breed af te spreken. Overigens dacht ik dat we eerder hadden vastgesteld dat 5.02 niet zou bestaan voor de KVK. maar kennelijk was "INF" ook voor de JV verplicht voor non-monitaries.

Rest ons alleen nog het standaardiseren van de manier van publiceren.

**Comment by tim-koelewijn** [comment]
Nauwelijks vragen hierover vanuit de markt. Dus voor nu geen actie hierop vanuit de WGNT.
