### ISSUE TITLE
Regel 2.02.11.12 - gebruik geen <xs:extension>

### ISSUE THREAD

**Issue by ekaats** [centrumvoorstandaarden/SBR_Werkgroep_NT#5]
De regel stelt dat <xs:extension> niet gebruikt moet worden.
https://github.com/centrumvoorstandaarden/SBR_Werkgroep_NT/blob/main/nta_regels/2_02_11_12.json

Dit is echter wel het geval bij (bd) tuples. Deze regel is (waarschijnlijk) ingevoerd omdat het niet de bedoeling is om XML niveau info toe te voegen. Passen we deze regel aan om gebruik in tuples toe te staan?

**Comment by ekaats** [comment]
Toevoegen verduidelijking: Behalve voor tuples.

**Comment by ekaats** [comment]
Hoe gaan we deze regel eenvoudig testbaar maken?
Toestaan wanneer attr 'base' = 'sbr:placeholder'?
Als <xs:extension> een ancestor heeft als <xs:complexType>?

Omdat we hier best dicht op de XML zitten, en de regel er is om te zorgen dat er op XML niveau niet iets wordt toegevoegd zou ik hier toch wel een goede fool-proof test op willen bedenken. False Negatives kunnen veel impact hebben voor deze regel.

**Comment by ekaatslogius** [comment]
Er is geen eenvoudige test te bedenken, dus deze gaat dicht en blijft een false positive icm tuples.
