### ISSUE TITLE
Regel 2.02.01.05 alleen voor standaard, terse en verbose

### ISSUE THREAD

**Issue by tim-koelewijn** [centrumvoorstandaarden/SBR_Werkgroep_NT#56]
De BD heeft voor NT17 meerdere documentation labels met dezelfde taal op 1 concept zitten. Dit heeft oa te maken met hergebruik van concepten over de verschillende berichtstromen heen en met het proces binnen de BD. Er is voor gekozen om de extra info die in andere documentatie zit op te nemen in de taxonomie. De BD ziet ook geen goede reden om niet meerdere documentation labels op 1 concept te hebben als extra uitleg bij een concept. Standaard software zoals XWand, Arelle en XmlSpy  gaan er prima mee om.
De reden voor deze regels lijkt te zijn dat een concept gepresenteerd moet worden in een rapport. Dan gaat het over het standaard, terse of wellicht het verbose label, maar niet documentation labels. XBRL zelf staat het ook gewoon toe.
Het voorstel is dan ook om de regel alleen voor standaard, terse en verbose te laten gelden.

**Comment by tim-koelewijn** [comment]
Voorstel is om documentation label en commentairy guidance als uitzondering op te nemen (en daarmee het lijstje om te draaien). De verschillende labels mogen niet semantisch afwijken.

**Comment by JacquesUrlus** [comment]
En de labels zouden niet gelijk mogen zijn.

**Comment by tim-koelewijn** [comment]
Moet wel in een RFC voor NTA voor NT18 worden meegenomen.

**Comment by tim-koelewijn** [comment]
EGG gaat hierover een RFC uitzetten.
