### ISSUE TITLE
Gebruik van labels / Labelroles

### ISSUE THREAD

**Issue by ekaats** [centrumvoorstandaarden/SBR_Werkgroep_NT#7]
Op de wiki staat een (zwaar) verouderde lijst met labelroles:
NL: https://sbr.wikixl.nl/index.php/Gebruik_van_labels
EN: https://sbr-en.wikixl.nl/index.php?title=Usage_of_labels

De lijst is verouderd, want er worden geen negated labels toegestaan en ook guidance documentation roles zijn niet toegestaan. Deze worden beide wel gebruikt in de NT.

Ik heb dit lijstje al eens opgenomen in 1 van de naamgevingsoverzichten:
https://github.com/centrumvoorstandaarden/SBR_Werkgroep_NT/blob/main/naamgeving/zonder_arcrole_vermelding.yaml

**Comment by ekaatslogius** [comment]
Pull request voor het verwijderen van onze best practice, aangezien we naar XII's guidance willen verwijzen:
https://github.com/centrumvoorstandaarden/SBR_Werkgroep_NT/pull/52

(willen we expliciet naar de guidance verwijzen? In dat geval zal er een nieuwe tekst voor in de plaats moeten komen)

**Comment by ekaatslogius** [comment]
We maken nog geen expliciete guidance; we koppelen terug aan de EGG dat we de XII guidance volgen op het gebied van label roles.
