### ISSUE TITLE
3.02.08.04 datatype moet de XML afgeleide naam in de naam opnemen

### ISSUE THREAD

**Issue by ekaats** [centrumvoorstandaarden/SBR_Werkgroep_NT#9]
Dit is een beetje rare regel wat mij betreft. Zo zou je bijvoorbeeld dit krijgen:

chamberOfCommerceRegistrationNumberItemType -> chamberOfCommerceRegistrationNumberStringItemType (erft van xbrli:stringItemType)
emailItemType -> emailStringItemType 

Geeft dit echt meer inzicht in wat de datatype is?

Voor van DTR afgeleide types is ook al duidelijk wat het is zonder te voldoen aan de regel:
nonNegativeMonetary20ItemType erft van dtr-types:nonNegativeMonetaryItemType

Om de regel echt goed uit te voeren, zouden we voor die dtr-types ook moeten achterhalen waarvan die worden afgeleid.

Mijn voorstel is om de regel af te schaffen om 1 redenen:
1. Duidelijkheid geeft de regel niet echt
2. Met DTR regels is het complex om het werkelijke XML itemtype te achterhalen.

**Comment by ekaatslogius** [comment]
Buiten gebruik gesteld.
